name = "Rectangle"
uuid = "9a9db56c-8f71-5460-add5-cb450131785e"
repo = "https://github.com/sambitdash/Rectangle.jl.git"
version = "0.1.3"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
